vich_uploader:
    db_driver: orm
    mappings:
        songs:
            uri_prefix: /upload/music
            upload_destination: '%kernel.project_dir%/public/upload/music'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
            inject_on_load: false
        images:
            uri_prefix: /upload/image
            upload_destination: '%kernel.project_dir%/public/upload/image'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
            inject_on_load: false
